---
title: "First Data visualization HW"
author: "Siyu"
date: "2023-01-12"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(tidyverse)
mpg
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))

#ggplot(data = <DATA>) + 
#  <GEOM_FUNCTION>(mapping = aes(<MAPPINGS>))
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class))
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, size = class))
#> Warning: Using size for a discrete variable is not advised.
```

```{r}
# Left
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, alpha = class))

# Right
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, shape = class))
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), color = "blue")
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = "blue"))
```

1. In the lines above, the ) is placed at the wrong place. It should be after y=hwy instead of color="blue". The line named the color blue instead of making the dots actually blue. 

2. categorical: manufacturer, model, displ, year, cyl, trans, drv, fl, class
continuous: cty, hwy

3. 
```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = hwy, y = cty), color = "blue")
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = hwy, y = hwy, shape = class, size = class), color = "blue")
```

```{r}
#left
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = hwy, y = cty, stroke=3), color = "red")
#right
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = hwy, y = cty, stroke=1), color = "red")
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = hwy, y = cty, color = year>5))
```